package lms;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Duc Anh
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_logout = new javax.swing.JLabel();
        lb_changepass = new javax.swing.JLabel();
        lb_usename = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mainMenu1 = new javax.swing.JButton();
        mainMenu2 = new javax.swing.JButton();
        mainMenu3 = new javax.swing.JButton();
        mainMenu4 = new javax.swing.JButton();
        mainMenu5 = new javax.swing.JButton();
        mainMenu6 = new javax.swing.JButton();
        mainMenu7 = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lb_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_logout.setForeground(new java.awt.Color(255, 255, 255));
        lb_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        lb_logout.setText("logout");
        lb_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_logoutMouseClicked(evt);
            }
        });

        lb_changepass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_changepass.setForeground(new java.awt.Color(255, 255, 255));
        lb_changepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/package_editors.png"))); // NOI18N
        lb_changepass.setText("change password");
        lb_changepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_changepassMouseClicked(evt);
            }
        });

        lb_usename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_usename.setForeground(new java.awt.Color(255, 255, 255));
        lb_usename.setText("Duc Anh");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Wellcome : ");

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jPanel5.setBackground(new java.awt.Color(12, 109, 173));
        jPanel5.setLayout(new java.awt.GridLayout(7, 1));

        mainMenu1.setText("jButton1");
        jPanel5.add(mainMenu1);

        mainMenu2.setText("jButton1");
        jPanel5.add(mainMenu2);

        mainMenu3.setText("jButton1");
        jPanel5.add(mainMenu3);

        mainMenu4.setText("jButton1");
        jPanel5.add(mainMenu4);

        mainMenu5.setText("jButton1");
        jPanel5.add(mainMenu5);

        mainMenu6.setText("jButton1");
        jPanel5.add(mainMenu6);

        mainMenu7.setText("jButton1");
        jPanel5.add(mainMenu7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lb_changepass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_logout))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lb_usename))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_usename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_changepass)
                    .addComponent(lb_logout))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        tabMain.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(tabMain, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this method calls Employees management panel
     *
     * @param evt
     */
private void mainMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu1MouseClicked

// TODO add your handling code here:
/////////////////////////////////

}//GEN-LAST:event_mainMenu1MouseClicked
    /**
     * this method calls Books Management panel
     *
     * @param evt
     */
private void mainMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu4MouseClicked

    // TODO add your handling code here:
    /////////////////////////////////

}//GEN-LAST:event_mainMenu4MouseClicked
    /**
     * this method calls Student Management panel
     *
     * @param evt
     */
private void mainMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu2MouseClicked

 for (int i = 0; i < tabMain.getTabCount(); i++)//GEN-LAST:event_mainMenu2MouseClicked
{
        }
        ////////////////////////////////////////////
    }

    /**
     *
     * this method calls Issue management Panel
     *
     * @param evt
     */
private void mainMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu5MouseClicked

    // TODO add your handling code here:
    //////////////////////////////////
}//GEN-LAST:event_mainMenu5MouseClicked
    /**
     *
     * this method will call Return Management panel
     *
     * @param evt
     */
private void mainMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu6MouseClicked
// TODO add your handling code here:
   for (int i = 0; i < tabMain.getTabCount(); i++)//GEN-LAST:event_mainMenu6MouseClicked
   {
        }
        /////////////////////////////////////////////
    }

    /**
     *
     * this method will call Publisher Management Panel
     *
     * @param evt
     */
private void mainMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu3MouseClicked
// TODO add your handling code here:
////////////////////////////////////////

}//GEN-LAST:event_mainMenu3MouseClicked

    /**
     *
     * this method will call reports panel
     *
     * @param evt
     */
private void mainMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenu7MouseClicked
// TODO add your handling code here:
    ////////////////////////////////////////


}//GEN-LAST:event_mainMenu7MouseClicked
    /**
     *
     * this method will call when you want to exit the programe
     *
     * @param evt
     */
private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    if (JOptionPane.showConfirmDialog(null, "Do you want to Exit this programe ?", "Delete Student!", JOptionPane.OK_CANCEL_OPTION) == 0) {
        this.dispose();
    }// TODO add your handling code here:
    /////////////////////////////////////////
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
////////////////////////////////

}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void lb_changepassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_changepassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_changepassMouseClicked

    private void lb_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_logoutMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Runtime.getRuntime().exec("hh.exe " + System.getProperty("user.dir") + "/help.chm");
        } catch (IOException ex) {

        }
// TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_changepass;
    private javax.swing.JLabel lb_logout;
    private javax.swing.JLabel lb_usename;
    private javax.swing.JButton mainMenu1;
    private javax.swing.JButton mainMenu2;
    private javax.swing.JButton mainMenu3;
    private javax.swing.JButton mainMenu4;
    private javax.swing.JButton mainMenu5;
    private javax.swing.JButton mainMenu6;
    private javax.swing.JButton mainMenu7;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables

}
