/*
 * Searchbook.java
 *
 * Created on June 15, 2016, 10:55 PM
 */
package lms;

import DatabaseWorker.ExecuteQuery;
import Objects.Books;
import Objects.Categories;
import Objects.Publishers;
import Support.SQLFileConfigHanlder;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duc Anh
 */
public class Searchbook extends javax.swing.JFrame {

    private ArrayList<Publishers> listPublisher;
    private ArrayList<Categories> listCategorieses;
    private ArrayList<Books> listBook;
    private ExecuteQuery exeQ;

    /**
     * Creates new form Searchbook
     */
    public Searchbook() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
        
        initData();
        loadView();
    }

    private void initData() {
        exeQ = ExecuteQuery.getInstance();

        listBook = new ArrayList<>();
        listBook = exeQ.getAllBooks();

        listCategorieses = new ArrayList<>();
        listCategorieses = exeQ.getAllCategories();

        listPublisher = new ArrayList<>();
        listPublisher = exeQ.getAllPublisher();
    }

    private void loadView() {
        if (listBook != null) {
            DefaultTableModel model;
            model = (DefaultTableModel)this.tb_books.getModel();
            listBook.stream().forEach((b) -> {
                model.addRow(new Object[]{b.getTitle(), b.getAuthorName(), b.getCategory().getCateName(), b.getPublisher().getPubName(), b.getNumberOfCopy()});
            });
            tb_books = new JTable(model);
        }

        if (listCategorieses != null) {
            cb_category.insertItemAt("", 0);
            listCategorieses.stream().forEach((c) -> {
                cb_category.addItem(c.getCateName());
            });
        }

        if (listPublisher != null) {
            cb_publisher.insertItemAt("", 0);
            listPublisher.stream().forEach((p) -> {
                cb_publisher.addItem(p.getPubName());
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsearch = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        edt_title = new javax.swing.JTextField();
        btn_search_book = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        edt_author = new javax.swing.JTextField();
        cb_category = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_publisher = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btn_display_all_book = new javax.swing.JButton();
        btn_close_searchbook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_books = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlsearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Add A New Class"), "Search Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N
        pnlsearch.setForeground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Category :");

        btn_search_book.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        btn_search_book.setForeground(new java.awt.Color(0, 102, 255));
        btn_search_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N
        btn_search_book.setText("Search");
        btn_search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_bookActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Publisher :");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Title :");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Author :");

        btn_display_all_book.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        btn_display_all_book.setForeground(new java.awt.Color(0, 102, 255));
        btn_display_all_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/displayall.png"))); // NOI18N
        btn_display_all_book.setText("Displayall");
        btn_display_all_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_display_all_bookActionPerformed(evt);
            }
        });

        btn_close_searchbook.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        btn_close_searchbook.setForeground(new java.awt.Color(0, 102, 255));
        btn_close_searchbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btn_close_searchbook.setText("Close");
        btn_close_searchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close_searchbookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlsearchLayout = new javax.swing.GroupLayout(pnlsearch);
        pnlsearch.setLayout(pnlsearchLayout);
        pnlsearchLayout.setHorizontalGroup(
            pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsearchLayout.createSequentialGroup()
                .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsearchLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_title)
                            .addComponent(cb_category, 0, 202, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlsearchLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlsearchLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(204, 204, 204))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsearchLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_search_book)
                        .addGap(32, 32, 32)
                        .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edt_author, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlsearchLayout.createSequentialGroup()
                                .addComponent(btn_display_all_book)
                                .addGap(36, 36, 36)
                                .addComponent(btn_close_searchbook)))))
                .addContainerGap())
        );
        pnlsearchLayout.setVerticalGroup(
            pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cb_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(pnlsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search_book, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_display_all_book, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close_searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tb_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "Category", "Publisher", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_books.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_books);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search_bookActionPerformed

    private void btn_display_all_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_display_all_bookActionPerformed
        // TODO add your handling code here:
        tb_books = new JTable();
        if (listBook != null) {
            DefaultTableModel model;
            model = (DefaultTableModel)this.tb_books.getModel();
            listBook.stream().forEach((b) -> {
                model.addRow(new Object[]{b.getTitle(), b.getAuthorName(), b.getCategory().getCateName(), b.getPublisher().getPubName(), b.getNumberOfCopy()});
            });
            tb_books = new JTable(model);
        }
    }//GEN-LAST:event_btn_display_all_bookActionPerformed

    private void btn_close_searchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close_searchbookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_close_searchbookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close_searchbook;
    private javax.swing.JButton btn_display_all_book;
    private javax.swing.JButton btn_search_book;
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JComboBox<String> cb_publisher;
    private javax.swing.JTextField edt_author;
    private javax.swing.JTextField edt_title;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlsearch;
    private javax.swing.JTable tb_books;
    // End of variables declaration//GEN-END:variables

}
